#!/usr/bin/env python3
"""Refresh the vendored trio-capability snapshot (backend/picker_capabilities.json).

Source: https://eqltools.com/picker/data.js, eqltools.com's own build
artifact. Their robots.txt asks one thing of anyone building on it -- "Cite
eqltools.com" -- which NOTICE.md and the advisor output both do.

VENDORED, never fetched at runtime. The file's own header says "generated by
pipeline ... do not hand-edit", so the format can change without notice; it
would be their bandwidth on every consult; and the packaged .exe has to work
offline. Same reasoning as backend/zem_levels.wiki, and this mirrors
scripts/refresh_zem.py.

What is dropped, and why it is not squeamishness:

- tierCC / tierDps / tierHeal are sealed "chat" -- letter grades with a prose
  justification, sourced from community discussion. This app gates model
  output against fact; feeding it graded consensus inverts that.
- manaPool / plate / tone / weaponCaps / tankModel are ratings and model
  values, not level-gated abilities. "You get plate at level None" is the
  kind of nonsense that costs an advisor its credibility.

What is deliberately KEPT even though it has no level: `track` is
{BRD, DRU, RNG} with empty entries. Membership in byClass is the capability;
`level` is optional detail. Filtering on "level is None" -- which is what
this was originally designed to do -- would delete track outright and make
every trio report that it lacks tracking, including a Ranger's.

Run from the repo root:  python scripts/refresh_picker.py
"""
import json
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from backend.capabilities import SNAPSHOT, load  # noqa: E402

URL = "https://eqltools.com/picker/data.js"

# Sealed "chat": graded opinion, not data.
DROP_SEALS = {"chat"}
# Ratings and model values rather than abilities.
DROP_NAMES = {"manaPool", "plate", "tone", "weaponCaps", "tankModel"}
# Per-class fields worth carrying: when you get it, how good it is at cap,
# and what it lands on. `ladder` is left behind -- it doubles the size for
# detail the advisor does not read.
KEEP_FIELDS = ("level", "best", "target")


def extract(js: str) -> dict:
    """The PICKER object out of the build artifact."""
    body = js[js.index("{"):]
    return json.loads(body[:body.rindex("}") + 1])


def trim(picker: dict) -> dict:
    caps = {}
    for name, v in (picker.get("capabilities") or {}).items():
        if name in DROP_NAMES or v.get("seal") in DROP_SEALS:
            continue
        if "byClass" not in v:
            continue
        row = {"byClass": {c: {k: e[k] for k in KEEP_FIELDS if k in e}
                           for c, e in v["byClass"].items()}}
        for k in ("seal", "note"):
            if v.get(k):
                row[k] = v[k]
        caps[name] = row
    return {"source": URL,
            "attribution": "Data from eqltools.com — cite eqltools.com",
            "meta": picker.get("meta", {}),
            "capabilities": caps}


def main() -> int:
    old = load() or {}
    old_caps = old.get("capabilities", {})
    req = urllib.request.Request(URL, headers={"User-Agent": "WarCounsel"})
    try:
        js = urllib.request.urlopen(req, timeout=45).read().decode("utf-8")
    except Exception as exc:
        print(f"fetch failed: {exc}")
        return 1
    try:
        snap = trim(extract(js))
    except Exception as exc:
        print(f"refused: the artifact did not parse ({exc}) -- "
              "snapshot untouched")
        return 1

    new_caps = snap["capabilities"]
    if not new_caps:
        print("refused: the fetched file parses to ZERO capabilities "
              "(format changed) -- snapshot untouched")
        return 1
    if old_caps and len(new_caps) < len(old_caps) * 0.75:
        print(f"refused: {len(new_caps)} capabilities is a big drop from the "
              f"current {len(old_caps)} -- look at the file before overwriting")
        return 1

    SNAPSHOT.write_text(json.dumps(snap, indent=1, sort_keys=True) + "\n",
                        encoding="utf-8")
    gained = sorted(set(new_caps) - set(old_caps))
    lost = sorted(set(old_caps) - set(new_caps))
    print(f"wrote {SNAPSHOT} — {SNAPSHOT.stat().st_size:,} bytes, "
          f"{len(new_caps)} capabilities (was {len(old_caps)})")
    print("  spell patch: %s" % snap["meta"].get("spellPatch", "?"))
    print("  wiki mirror: %s"
          % (snap["meta"].get("generatedFrom", {}).get("wiki-mirror", "?")))
    if gained:
        print("  added:   " + ", ".join(gained))
    if lost:
        print("  removed: " + ", ".join(lost))
    if not gained and not lost:
        print("  no capability changes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
